// Generated by scripts/fit_flight_numbers.py — do not edit by hand.
// Calibrated to manufacturer flight numbers of 43 pro discs; see data/flight_fit.json for stats & caveats.
const FLIGHT_FIT = {
 "speed": {
  "features": {
   "rw": 0.71927,
   "dia": -0.01596
  },
  "intercept": -1.46374,
  "clamp": [
   1,
   14.5
  ],
  "train_r2": 0.957,
  "loo_rmse": 0.811
 },
 "glide": {
  "features": {
   "rw": 0.15834,
   "dia": 0.17813,
   "pr": 10.6401,
   "dome": -0.00691
  },
  "intercept": -41.89062,
  "clamp": [
   1,
   7
  ],
  "train_r2": 0.719,
  "loo_rmse": 0.736
 },
 "turn": {
  "features": {
   "pr": -11.55478,
   "h": -0.01104,
   "rw": -0.09124
  },
  "intercept": 7.31279,
  "clamp": [
   -5,
   1
  ],
  "train_r2": 0.791,
  "loo_rmse": 0.459
 },
 "fade": {
  "features": {
   "rw": 0.08581,
   "pr": -12.85525,
   "dome": -0.01089
  },
  "intercept": 7.68279,
  "clamp": [
   0,
   5
  ],
  "train_r2": 0.821,
  "loo_rmse": 0.451
 }
};
