"""Regenerate cfd_sweep.js from cfd/bigsweep/dataset.csv.

One CFD_SWEEP entry per geometry: shape params + per-alpha Cl/Cd/Cm arrays,
sorted by alpha. Run after cfd/bigsweep/collect.py refreshes dataset.csv.
"""
import csv, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEATS = ["rim_width_mm", "rim_shoulder_mm", "parting_line_mm",
         "dome_mm", "plate_thick_mm", "nose_radius_mm"]

geoms = {}
with open(os.path.join(ROOT, "cfd", "bigsweep", "dataset.csv")) as f:
    for r in csv.DictReader(f):
        g = geoms.setdefault(r["id"], {"id": r["id"],
                                       "p": {k: float(r[k]) for k in FEATS},
                                       "rows": []})
        g["rows"].append((float(r["alpha_deg"]), float(r["Cl"]),
                          float(r["Cd"]), float(r["Cm"])))

entries = []
for gid in sorted(geoms):
    g = geoms[gid]
    rows = sorted(g["rows"])
    entries.append({"id": g["id"], "p": g["p"],
                    "a": [r[0] for r in rows],
                    "cl": [r[1] for r in rows],
                    "cd": [r[2] for r in rows],
                    "cm": [r[3] for r in rows]})

n_runs = sum(len(e["a"]) for e in entries)
js = ("// Raw CFD sweep results: steady RANS (k-omega SST), one entry per geometry.\n"
      "// Generated by scripts/build_cfd_sweep_js.py from cfd/bigsweep/dataset.csv\n"
      "// (cfd/bigsweep/collect.py output).\n"
      "const CFD_SWEEP=" + json.dumps(entries) + ";\n")
out = os.path.join(ROOT, "cfd_sweep.js")
with open(out, "w") as f:
    f.write(js)
print(f"wrote {out}: {len(entries)} geometries, {n_runs} runs ({len(js)} bytes)")
