#!/usr/bin/env python3
"""
Build the app's embedded disc database from the PDGA certified-discs CSV.

Inputs : data/pdga_approved_discs.csv
         (export of https://www.pdga.com/technical-standards/equipment-certification/discs/export
          — fetch with a browser User-Agent; the default curl UA gets a 403)
         data/pro_discs.json — curated pro-disc presets (single source of truth)
Outputs: disc_db.js   — `const DISC_DB = [...]` consumed by disc_designer.html
         pro_discs.js — `const PRO_DISCS = [...]` consumed by disc_designer.html

Each row keeps only what the designer needs, in millimetres/grams:
  [manufacturer, model, dia_mm, height_mm, rim_depth_mm, rim_width_mm,
   inner_rim_dia_mm, max_weight_g, approved_year]

Rows missing any numeric measurement are dropped (a handful of vintage discs).

Refresh:
  curl -A "Mozilla/5.0" -o data/pdga_approved_discs.csv \
    "https://www.pdga.com/technical-standards/equipment-certification/discs/export"
  python3 scripts/build_disc_db.py
"""
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "pdga_approved_discs.csv"
OUT = ROOT / "disc_db.js"


def main() -> None:
    rows, dropped = [], 0
    with open(SRC, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            try:
                rows.append([
                    r["Manufacturer / Distributor"].strip(),
                    r["Disc Model"].strip(),
                    round(float(r["Diameter (cm)"]) * 10, 1),
                    round(float(r["Height (cm)"]) * 10, 1),
                    round(float(r["Rim Depth (cm)"]) * 10, 1),
                    round(float(r["Rim Thickness (cm)"]) * 10, 1),
                    round(float(r["Inside Rim Diameter (cm)"]) * 10, 1),
                    float(r["Max Weight (gr)"]),
                    int(r["Approved Date"].rsplit(", ", 1)[-1]),
                ])
            except (ValueError, KeyError):
                dropped += 1
    rows.sort(key=lambda x: (x[0], x[1]))

    body = ",\n".join(json.dumps(r, ensure_ascii=False) for r in rows)
    OUT.write_text(
        "// Generated by scripts/build_disc_db.py — do not edit by hand.\n"
        "// Source: PDGA certified-disc database export (see data/pdga_approved_discs.csv).\n"
        "// Fields: [manufacturer, model, dia_mm, height_mm, rim_depth_mm, rim_width_mm,\n"
        "//          inner_rim_dia_mm, max_weight_g, approved_year]\n"
        f"const DISC_DB = [\n{body}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.name}: {len(rows)} discs ({dropped} rows dropped for missing data)")

    pro = json.loads((ROOT / "data" / "pro_discs.json").read_text())["discs"]
    entries = ",\n".join(
        json.dumps({"cls": d["cls"], "mfr": d["mfr"], "name": d["name"],
                    "dia": d["dia"], "h": d["h"], "rd": d["rd"], "rw": d["rw"],
                    "wt": d["wt"], "fl": d["flight"]}, ensure_ascii=False)
        for d in pro)
    (ROOT / "pro_discs.js").write_text(
        "// Generated by scripts/build_disc_db.py from data/pro_discs.json — do not edit by hand.\n"
        "// Certified measurements (mm/g) + manufacturer flight numbers of the curated pro discs.\n"
        f"const PRO_DISCS = [\n{entries}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote pro_discs.js: {len(pro)} pro discs")


if __name__ == "__main__":
    sys.exit(main())
