"""Fit a COMPACT degree-2 polynomial surrogate (geom -> 7 aero coefficients)
and export it as a small JS file the browser app can load.

A 400-tree RandomForest is accurate but far too big to ship to the browser;
the coefficients are smooth functions of geometry, so a standardized degree-2
polynomial (28 terms per coefficient) captures most of the signal in ~200
numbers total. We print its k-fold CV next to the forest's so the compaction
cost is explicit.

Feature order (must match the JS exactly): rim_width, shoulder, parting,
dome, plate, nose.  Poly terms: [1] + x_i + x_i*x_j (i<=j) = 1+6+21 = 28.
"""
import json, os
import numpy as np
import pandas as pd

BS = os.path.dirname(os.path.abspath(__file__))
FEATS = ["rim_width_mm", "rim_shoulder_mm", "parting_line_mm",
         "dome_mm", "plate_thick_mm", "nose_radius_mm"]
TARGETS = ["CL0", "CLa", "CD0", "CDa", "alpha0", "CM0", "CMa"]
RIDGE = 1e-3


def poly2(Xs):
    """standardized X (n,6) -> design matrix (n,28) in the canonical term order."""
    n, d = Xs.shape
    cols = [np.ones(n)]
    cols += [Xs[:, i] for i in range(d)]
    for i in range(d):
        for j in range(i, d):
            cols.append(Xs[:, i] * Xs[:, j])
    return np.column_stack(cols)


def ridge_fit(P, y):
    A = P.T @ P + RIDGE * np.eye(P.shape[1])
    return np.linalg.solve(A, P.T @ y)


def kfold_r2(X, y, mean, std, k=8, seed=0):
    rng = np.random.default_rng(seed)
    idx = rng.permutation(len(y))
    folds = np.array_split(idx, k)
    yp = np.zeros_like(y)
    for f in folds:
        tr = np.setdiff1d(idx, f)
        Ptr = poly2((X[tr] - mean) / std)
        w = ridge_fit(Ptr, y[tr])
        yp[f] = poly2((X[f] - mean) / std) @ w
    ss_res = np.sum((y - yp) ** 2); ss_tot = np.sum((y - y.mean()) ** 2)
    return 1 - ss_res / ss_tot if ss_tot else float("nan")


def main():
    df = pd.read_csv(os.path.join(BS, "coeff_table.csv"))
    X = df[FEATS].to_numpy(float)
    mean, std = X.mean(0), X.std(0)
    std[std == 0] = 1.0

    # wind-tunnel bias correction (anchors/fit_anchors.py): the coarse mesh
    # carries a systematic level error; scale the lift and drag targets so the
    # exported surrogate sits on Kamaruddin's measured level. alpha0 = -CL0/CLa
    # is scale-invariant, so it needs no correction.
    bias_path = os.path.join(BS, "..", "anchors", "anchor_bias.json")
    kCL = kCD = 1.0
    if os.path.exists(bias_path):
        b = json.load(open(bias_path))
        kCL, kCD = b["kCL"], b["kCD"]
        print(f"applying anchor bias correction: kCL={kCL}  kCD={kCD}")
    SCALE = {"CL0": kCL, "CLa": kCL, "CD0": kCD, "CDa": kCD}

    out = {"features": FEATS, "mean": mean.round(5).tolist(),
           "std": std.round(5).tolist(), "targets": {},
           "bias_correction": {"kCL": kCL, "kCD": kCD,
                               "source": "anchors/anchor_bias.json (Kamaruddin wind tunnel)"}}
    print(f"{'coef':7} {'poly_cv_r2':>10}")
    Ps = poly2((X - mean) / std)
    n_geo = df.shape[0]
    for t in TARGETS:
        y = df[t].to_numpy(float)
        w = ridge_fit(Ps, y) * SCALE.get(t, 1.0)   # full-data weights for export
        r2 = kfold_r2(X, y, mean, std)
        out["targets"][t] = [round(float(v), 6) for v in w]
        print(f"{t:7} {r2:>10.3f}")

    js = ("// CFD-surrogate: geometry -> aero coefficients (degree-2 poly).\n"
          f"// Generated by cfd/bigsweep/export_surrogate_js.py from the {n_geo}-geometry\n"
          "// CFD sweep, lift/drag scaled to the Kamaruddin wind-tunnel level\n"
          "// (see bias_correction). Feature order and 28-term poly layout are\n"
          "// fixed; see cfdAero().\n"
          "const CFD_SURROGATE = " + json.dumps(out) + ";\n")
    path = os.path.join(BS, "..", "..", "cfd_surrogate.js")
    with open(os.path.normpath(path), "w") as f:
        f.write(js)
    print(f"\nwrote {os.path.normpath(path)}  ({len(js)} bytes)")


if __name__ == "__main__":
    main()
